# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: configs
    label: Supported configurations
    hide: true
    files:
      - file: configs/supportedFields.json
        label: supported_fields
        name: supported_fields
        fields:
          - label: supported_fields
            name: supported_fields
            widget: list
            fields: 
              - label: name
                name: name
                widget: string
              - label: id
                name: id
                widget: string
              - label: type
                name: type
                widget: string
      - file: configs/validators.json
        label: validators
        name: validators
        hide: true
        fields:
          - label: validators
            name: validators
            allow_add: false
            widget: list
            fields: 
              - label: name
                name: name
                widget: string
              - label: id
                name: id
                widget: string
              - label: regex
                name: regex
                widget: string

  - name: "Country Configs"
    label: "Configs"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "configs/xz.json"
        label: "XZ Settings"
        name: "xz-settings"
        fields:
          - label: Self-Service
            name: self-service
            widget: list
            fields: 
              - label: Field
                name: field
                widget: relation
                collection: configs
                file: supported_fields
                search_fields: ["supported_fields.*.name"]
                display_fields: ["supported_fields.*.name"]
                value_field: "supported_fields.*.id"
              - label: Validator
                name: validator
                widget: relation
                collection: configs
                file: validators
                multiple: true
                search_fields: ["validators.*.name"]
                display_fields: ["validators.*.name"]
                value_field: "validators.*.id"
              - label: Required
                name: required
                widget: boolean
        
